name: Run Examples


on:
  pull_request:
  workflow_dispatch:
  push:
    tags-ignore:
      - v*
jobs:
  scala-cli-examples:
    strategy:
      matrix:
        example_dir: ["ramp-vus-scenario", "scala-cli-helloworld", "single-request"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3  
        with:
          fetch-depth: 0  
      - uses: coursier/cache-action@v6.4
      - uses: VirtusLab/scala-cli-setup@v1.5
      - run: scala-cli --power package  examples/${{ matrix.example_dir }}/example.scala --js --js-emit-source-maps --js-module-kind esmodule -f --js-no-opt
      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: example.js
  mill-example:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3  
        with:
          fetch-depth: 0  
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:17
          apps: mill
      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Build simulation file
        run: mill helloworld.fastOpt
        working-directory: ./mill-helloworld
      - name: Run K6 simulation
        run: mill helloworld.runK6test
        working-directory: ./mill-helloworld
  sbt-example:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3  
        with:
          fetch-depth: 0  
      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v3.1
      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Build simulation file
        run:  sbt fastOptJS
        working-directory: ./sbt-helloworld
      - name: Run K6 simulation
        run:  sbt runK6test
        working-directory: ./sbt-helloworld
